-- Enable pgvector extension for embeddings
create extension if not exists vector;

-- Table to store past incidents (used for RAG)
create table if not exists knowledge_base (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  content text not null,
  category text not null,  -- e.g. 'api_error', 'data_sync', 'auth', 'performance'
  resolution text,
  embedding vector(384),   -- sentence-transformers all-MiniLM-L6-v2 dimension
  created_at timestamp with time zone default now()
);

-- Table to store incoming support tickets
create table if not exists tickets (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  description text not null,
  submitted_at timestamp with time zone default now()
);

-- Table to store full incident reports generated by agents
create table if not exists incident_reports (
  id uuid default gen_random_uuid() primary key,
  ticket_id uuid references tickets(id),
  severity text,           -- P1, P2, P3, P4
  category text,
  triage_output jsonb,
  log_analysis_output jsonb,
  root_cause_output jsonb,
  resolution_output jsonb,
  similar_incidents jsonb, -- RAG results
  created_at timestamp with time zone default now()
);

-- Function for semantic similarity search (used by RAG)
create or replace function match_knowledge_base (
  query_embedding vector(384),
  match_threshold float default 0.5,
  match_count int default 3
)
returns table (
  id uuid,
  title text,
  content text,
  category text,
  resolution text,
  similarity float
)
language sql stable
as $$
  select
    id,
    title,
    content,
    category,
    resolution,
    1 - (embedding <=> query_embedding) as similarity
  from knowledge_base
  where 1 - (embedding <=> query_embedding) > match_threshold
  order by similarity desc
  limit match_count;
$$;
